#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Project Euler Problem #44
"""
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
"""
    
def genPentagonalList(n_max):
    return [x*(3*x-1)/2 for x in xrange(1,n_max+1)]

def pentagonal(x):
    return x*(3*x-1)/2

if __name__ == "__main__":
    
    pset = set(genPentagonalList(10))
    if (pentagonal(4) + pentagonal(7)) in pset\
    and not (pentagonal(4) - pentagonal(7)) in pset:
        print "Test passed."
    else:
        print "Test failed!"
    
    results = []
    maxN    = 10000
    plist   = genPentagonalList(maxN)
    pset    = set(plist)
    length  = len(plist)
    for i in xrange(1,length):
        for j in xrange(i+1,length):
            a = plist[i]
            b = plist[j]
            if a+b in pset and b-a in pset:
                results.append(b-a)
                print i,j,a,b,b-a
                 
    print "The answer to #44 is:%s" % sorted(results)[0]
